### PR TITLE
Directly return responses from Local Cluster client

### LINKED ISSUE #132: [BUG]Unable to call aggregation in ml-commons API /_plugins/_ml/models/_search API
### What is the bug?
When we use aggregation in /_plugins/_ml/models/_search API, it returns error like

```
{
    "error": {
        "root_cause": [
            {
                "type": "status_exception",
                "reason": "Fail to search model version"
            }
        ],
        "type": "status_exception",
        "reason": "Fail to search model version"
    },
    "status": 500
}
```

### How can one reproduce the bug?
In Opensearch 2.19 or 3.0.0 alpha1, we create any connector and corresponding remote ml model. Then we call 
```
POST /_plugins/_ml/models/_search
{
  "size": 0,
  "aggs": {
    "unique2_connector_names": {
      "terms": {
        "field": "connector.name.keyword",
        "size": 10000
      }
    }
  }
}
```
Then we will get error.

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
I think it's related to current repo because In ml commons, In line 142 in `MLSearchHandler`  we use `sdkClient.searchDataObjectAsync`  from library [remote-metadata-sdk](https://github.com/opensearch-project/opensearch-remote-metadata-sdk). After changing it to `cient.search` , it works. Also, I fetch the search request body in the debug mod and call `_search` directly, it also works. So I think the problem is from the [remote-metadata-sdk](https://github.com/opensearch-project/opensearch-remote-metadata-sdk) library.

### PR DESCRIPTION
**Pull request by dbwiddis**
WIP: Still need to address bulk response

### Description

Avoids the serializing and deserializing of responses in the (default) client.  This avoids parsing issues as well as loss of runtime information of subclasses.

### Issues Resolved

Alternate solution to resolve #132 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dhrubo-os** [comment]
I assume from the consumer side like ML-Common/Flow framework we don't have to make any changes based on this, right?

**Comment by dbwiddis** [comment]
> I assume from the consumer side like ML-Common/Flow framework we don't have to make any changes based on this, right?

I've made an effort to be backwards compatible for the current implementation.  I'm still debating whether to mark the parser methods as deprecated.

So while you don't "have to" make changes, it would be a Good Thing™️ to replace the pattern:
```
return response.parser() == null ? null : GetResponse.fromXContent(response.parser());
```
with
```
return response.getResponse();
```

**Comment by dhrubo-os** [comment]
> > I assume from the consumer side like ML-Common/Flow framework we don't have to make any changes based on this, right?
> 
> I've made an effort to be backwards compatible for the current implementation. I'm still debating whether to mark the parser methods as deprecated.
> 
> So while you don't "have to" make changes, it would be a Good Thing™️ to replace the pattern:
> 
> ```
> return response.parser() == null ? null : GetResponse.fromXContent(response.parser());
> ```
> 
> with
> 
> ```
> return response.getResponse();
> ```

`return response.getResponse();` will that be also compatible with other client implementation like DDBClient?

**Comment by dbwiddis** [comment]
> `return response.getResponse();` will that be also compatible with other client implementation like DDBClient?

Yes, this implementation basically encodes the "if we don't have the NodeClient response, create one from a parser."

The possible `IOException` will need to be handled (but I think it's already done!)

Only really potentially controversial question is whether it is even possible for the response to be null.   I don't think so but the code allows for that.

**Comment by dbwiddis** [comment]
@dhrubo-os I flipped this to ready for review as it's _mostly_ complete.  The one thing I am still questioning is the handling of failures in the BulkResponse.  In the original, it seems the item `getResponse()` can return null on failure (`BulkItemResponse` is non-null and reports failure while the `getResponse()` (index/update/delete) value is null) and I haven't looked at that enough to convince myself we're faithfully matching it.  I'll let you know when I'm happy with that.

**Comment by dbwiddis** [comment]
@dhrubo-os @arjunkumargiri this is ready for review

File: core/src/main/java/org/opensearch/remote/metadata/client/BulkDataObjectResponse.java [hunk 1]
```diff
@@ -88,11 +139,33 @@ public boolean hasFailures() {
...
     /**
      * Returns the parser
      * @return the parser
      */
     public XContentParser parser() {
+        if (this.parser == null) {
+            try {
+                return SdkClientUtils.createParser(bulkResponse);
+            } catch (IOException | NullPointerException e) {
+                return null;
```
Comment (dhrubo-os) [inline core/src/main/java/org/opensearch/remote/metadata/client/BulkDataObjectResponse.java:166]: What is the cascade effect if we just return null to the downstream?

Comment (dbwiddis) [reply core/src/main/java/org/opensearch/remote/metadata/client/BulkDataObjectResponse.java:166]: This is one of those “should never happen” situations. 

The SDKClientUtil null checks it if it’s used.  

Otherwise the caller has to null check.

Comment (dbwiddis) [reply core/src/main/java/org/opensearch/remote/metadata/client/BulkDataObjectResponse.java:166]: Alternative is throwing an unchecked exception the caller doesn’t know to catch, or a checked exception that will never happen that we force the caller to handle

**Comment by dhrubo-os** [comment]
Can we please add more test details in the issue description? 

Have we tried to make any aggregated search with any Plugin like FF/ml-commons with this changes?

**Comment by dhrubo-os** [comment]
Can we also test the bulk as well as we made changes there too?

File: remote-client/src/main/java/org/opensearch/remote/metadata/client/impl/RemoteClusterIndicesClient.java [hunk 2]
```diff
@@ -564,7 +562,7 @@ private XContentParser createParser(JsonpSerializable obj) throws IOException {
         try (JsonGenerator generator = mapper.jsonProvider().createGenerator(stringWriter)) {
             mapper.serialize(obj, generator);
         }
-        return jsonXContent.createParser(NamedXContentRegistry.EMPTY, DeprecationHandler.IGNORE_DEPRECATIONS, stringWriter.toString());
+        return SdkClientUtils.createParser(stringWriter.toString());
```
Comment (dhrubo-os) [inline remote-client/src/main/java/org/opensearch/remote/metadata/client/impl/RemoteClusterIndicesClient.java:565]: I assume DDB client parsing logic is different which is why we aren't adding the same changes to the ddb client?

Comment (dbwiddis) [reply remote-client/src/main/java/org/opensearch/remote/metadata/client/impl/RemoteClusterIndicesClient.java:565]: Actually DDB client logic is identical and we should make this same change there.

This isn't so much a change as a refactoring, moving the `jsonXContent.createParser` code to the `SdkClientUtils` class and delegating the call there.

The reason it was less important for the bug fix is that DDB doesn't implement search.

**Comment by dbwiddis** [comment]
> Can we also test the bulk as well as we made changes there too?

There is no change to the functionality of bulk, which is thoroughly unit tested. In fact, the change revealed a bug in the test (wrong type) which became more obvious with the direct pass-through.

**Comment by dbwiddis** [comment]
> Can we please add more test details in the issue description?

I started #132 by writing a unit test that failed without the fix and that test is carried over here.

Not clear what you're asking for?  A sanity check with Flow Framework?  I've done that, as well as run the tenant aware integration tests using the new client.

> Have we tried to make any aggregated search with any Plugin like FF/ml-commons with this changes?

Yes, although there are likely many different combinations.

**Comment by dhrubo-os** [comment]
>Not clear what you're asking for? A sanity check with Flow Framework? I've done that, as well as run the tenant aware integration tests using the new client.

Yeah this is what I was asking. If you ran the tenant aware integration tests with the new changes of PR, I'm good with this. Thanks for clarifying.

**Comment by dbwiddis** [comment]
> So while you don't "have to" make changes

I should be more clear: you will need to change the search handler's code to the new getResponse() version to fix the aggregation bug in the local client with this PR

**Comment by dbwiddis** [comment]
Added integ test to ML Commons PR https://github.com/opensearch-project/ml-commons/pull/3516.

https://github.com/opensearch-project/ml-commons/pull/3516/commits/0bef7a9122f918da91a7db80fbcf8c007e2786a8 adds an integ test that uses an aggregation to search.  This results in the failure stack trace in #132 
```
  2> REPRODUCE WITH: ./gradlew ':opensearch-ml-plugin:integTest' --tests "org.opensearch.ml.rest.RestMLModelTenantAwareIT.testModelCRUD" -Dtests.seed=8663FF7406EA2943 -Dtests.security.manager=false -Dtests.locale=yrl-CO -Dtests.timezone=Australia/Lord_Howe -Druntime.java=21
  2> org.opensearch.client.ResponseException: method [GET], host [http://[::1]:61137], URI [/_plugins/_ml/models/_search], status line [HTTP/1.1 500 Internal Server Error]
    {"error":{"root_cause":[{"type":"status_exception","reason":"Fail to search model version"}],"type":"status_exception","reason":"Fail to search model version"},"status":500}

»  org.opensearch.core.common.ParsingException: Could not parse aggregation keyed as [unique_model_names]
»       at org.opensearch.search.aggregations.Aggregations.fromXContent(Aggregations.java:165) ~[opensearch-3.0.0-beta1-SNAPSHOT.jar:3.0.0-beta1-SNAPSHOT]

» WARN ][r.suppressed             ] [integTest-0] path: /_plugins/_ml/models/_search, params: {}
»  org.opensearch.OpenSearchStatusException: Fail to search model version
```

https://github.com/opensearch-project/ml-commons/pull/3516/commits/0e10ea8328379f02620f8ef2fefe324f7e4abe3e updates the calls to SdkClient search to directly return the search response.  The integ test passes.

**Comment by dbwiddis** [comment]
Ran a sanity test against ML Commons PR https://github.com/opensearch-project/ml-commons/pull/3516 branch deployed in OpenSearch 3.0.0-beta1 docker container

Created a connector and registered a model with that connector
```json
POST https://localhost:9200/_plugins/_ml/models/_register
{
  "name": "bedrock:embedding cohere model",
  "function_name": "remote",
  "description": "embedding open ai model",
  "connector_id": "5vYkXJYBhf97Ja-IYBpD"
}
```
```json
{
    "task_id": "6_YnXJYBhf97Ja-IFhpG",
    "status": "CREATED",
    "model_id": "7PYnXJYBhf97Ja-IFhp9"
}
```
Deployed the model
```json
POST https://localhost:9200/_plugins/_ml/models/7PYnXJYBhf97Ja-IFhp9/_deploy

{
    "task_id": "7vYtXJYBhf97Ja-I5hqc",
    "task_type": "DEPLOY_MODEL",
    "status": "COMPLETED"
}
```
Undeployed the model
```json
https://localhost:9200/_plugins/_ml/models/7PYnXJYBhf97Ja-IFhp9/_undeploy

{
    "6vhLaJ3pRDy773z0aZCXPA": {
        "stats": {
            "7PYnXJYBhf97Ja-IFhp9": "undeployed"
        }
    }
}
```
Undeployed the model again
```json
https://localhost:9200/_plugins/_ml/models/7PYnXJYBhf97Ja-IFhp9/_undeploy

{
    "6vhLaJ3pRDy773z0aZCXPA": {
        "stats": {
            "7PYnXJYBhf97Ja-IFhp9": "not_found"
        }
    }
}
```

Searched with an aggregation
```json
GET https://localhost:9200/_plugins/_ml/models/_search
{
  "size": 0,
  "aggs": {
    "unique_model_names": {
      "terms": {
        "field": "name.keyword",
        "size": 10000
      }
    }
  }
}

{
    "took": 9,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 1,
            "relation": "eq"
        },
        "max_score": null,
        "hits": []
    },
    "aggregations": {
        "unique_model_names": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
                {
                    "key": "bedrock:embedding cohere model",
                    "doc_count": 1
                }
            ]
        }
    }
}
```

**Review by dhrubo-os — APPROVED** [review]

**Comment by dbwiddis** [comment]
@dhrubo-os thanks for the approval!  Some quick follow-up:
1. I would recommend you cherry-pick https://github.com/opensearch-project/ml-commons/commit/0e10ea8328379f02620f8ef2fefe324f7e4abe3e into a PR on main branch.  This will directly pass search response for Local/NodeClient implementations.   You may consider doing similar for other wrappers over time, but this one is more "urgent" due to the search aggregation bug.
2. Without the cherry-pick recommended in (1) the parsing still requires a type hint.  We can't pass `typed_keys` on the ml search REST path because it's not allowed.  This may still impact the remote client and we may want to consider always adding that to the rest path when sending a search request via the client.
